# Generated by Django 6.0.7 on 2026-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='runner',
            field=models.CharField(blank=True, choices=[('', 'Без практики'), ('python', 'Python IDE (Pyodide)'), ('javascript', 'JavaScript-песочница'), ('terminal', 'Мини-терминал (bash/git/docker)'), ('sql', 'SQL-консоль (SQLite)')], default='', max_length=20, verbose_name='Практика в уроке'),
        ),
    ]
