# Generated by Django 6.0.7 on 2026-07-13 17:31

from django.db import migrations, models

import apps.assessments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_quiz_module_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/', validators=[apps.assessments.validators.validate_homework_file], verbose_name='Файл'),
        ),
    ]
