# Generated by Django 6.0.7 on 2026-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Даёт доступ к кабинету преподавателя: проверка ДЗ, прогресс учеников, чат.', verbose_name='Преподаватель'),
        ),
    ]
